#!/usr/bin/env python3
"""
gen_custom_registry.py — scan remotion/src/custom/*.tsx (agent-authored scene
components) and regenerate registry.tsx so the renderer can resolve a scene of
{"type":"custom","props":{"component":"<Name>"}} to its component.

Each custom file must be named <ComponentName>.tsx and DEFAULT-export the component.
Run this after the agent writes/edits custom scenes and before rendering
(build_storyboard.py calls it automatically).
"""
import os, glob, re

ROOT = os.path.expanduser("~/claude/content-engine/remotion/src/custom")
REG = os.path.join(ROOT, "registry.tsx")


def main():
    files = sorted(f for f in glob.glob(os.path.join(ROOT, "*.tsx"))
                   if os.path.basename(f) != "registry.tsx")
    names = []
    for f in files:
        name = os.path.splitext(os.path.basename(f))[0]
        if not re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", name):
            print(f"skip (bad component name): {name}")
            continue
        names.append(name)

    lines = [
        "// AUTO-GENERATED by scripts/gen_custom_registry.py — do not edit by hand.",
        '// Maps a custom scene\'s component name -> the agent-authored React component.',
        'import React from "react";',
    ]
    for n in names:
        lines.append(f'import {n} from "./{n}";')
    lines.append("export const CUSTOM: Record<string, React.FC<any>> = {")
    for n in names:
        lines.append(f"  {n}: {n},")
    lines.append("};")
    open(REG, "w").write("\n".join(lines) + "\n")
    print(f"registry.tsx: {len(names)} custom scene(s): {', '.join(names) or '(none)'}")


if __name__ == "__main__":
    main()
