#!/usr/bin/env python3
"""
trends.py — weekly EXTERNAL trend analysis. Uses the TRENDS-scanner account session (accounts.trends,
a separate account from the posting one) to pull the top reels in the channel's niche, then
synthesizes memory/TRENDS.md — which the
ideation reasoner reads (alongside LEARNINGS.md) so daily videos reflect what's working on IG now.

    python scripts/trends.py            # run weekly (cron)
    python scripts/trends.py --deep     # also download+transcribe the top few for hook teardown

Reads niche hashtags + cookie path from config.json (accounts.trends / trends.*).
"""
import argparse, json, os, subprocess, sys

ROOT = os.path.expanduser("~/claude/content-engine")
FIND = os.path.expanduser("~/claude/instagram/scripts/find_reels.py")
ANALYZE = os.path.expanduser("~/claude/instagram/scripts/analyze_reel.py")
PY = sys.executable


def cfg():
    return json.load(open(f"{ROOT}/config.json"))


def find(hashtag, cookies, limit):
    env = dict(os.environ, IG_COOKIES=os.path.expanduser(cookies))
    try:
        out = subprocess.run([PY, FIND, "--hashtag", hashtag, "--sort", "views", "--limit", str(limit)],
                             capture_output=True, text=True, env=env, timeout=120)
        return json.loads(out.stdout) if out.stdout.strip().startswith("[") else []
    except Exception as e:
        print(f"[trends] {hashtag}: {e}", file=sys.stderr)
        return []


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--deep", action="store_true", help="download+transcribe the top few reels")
    a = ap.parse_args()
    c = cfg()
    cookies = c.get("accounts", {}).get("trends", {}).get("cookies")
    tcfg = c.get("trends", {})
    tags = tcfg.get("hashtags", ["techtok", "coding", "systemdesign"])
    per = tcfg.get("per_tag", 12)
    top_n = tcfg.get("top_n", 25)

    if not cookies or not os.path.exists(os.path.expanduser(cookies)):
        sys.exit(f"[trends] no trends-account cookie file ({cookies}) — set accounts.trends.cookies "
                 f"in config.json and log that account in first.")

    reels = []
    for t in tags:
        got = find(t, cookies, per)
        print(f"[trends] #{t}: {len(got)} reels")
        reels += got

    seen = {}
    for r in reels:
        sc = r.get("shortcode")
        if sc and sc not in seen:
            seen[sc] = r
    top = sorted(seen.values(), key=lambda r: (r.get("views") or 0), reverse=True)[:top_n]
    if not top:
        print("[trends] no reels fetched (cookies expired/blocked?) — keeping existing TRENDS.md")
        return

    data = [{"views": r.get("views"), "likes": r.get("likes"),
             "caption": (r.get("caption") or "")[:220]} for r in top]

    # optional deep teardown of the very top few (transcripts add hook signal)
    if a.deep:
        env = dict(os.environ, IG_COOKIES=os.path.expanduser(cookies))
        urls = [r["url"] for r in top[:5] if r.get("url")]
        if urls:
            subprocess.run([PY, ANALYZE] + urls + ["--outdir", "/tmp/trend_reels", "--model", "base"],
                           env=env, timeout=900)

    prompt = open(f"{ROOT}/prompts/trends.md").read() + "\n\nTOP REELS (JSON):\n" + json.dumps(data, indent=2)
    out = subprocess.run(["claude", "-p", prompt, "--output-format", "text", "--dangerously-skip-permissions"],
                         capture_output=True, text=True, timeout=600)
    md = out.stdout.strip()
    if not md:
        print("[trends] synthesis empty; keeping old TRENDS.md", file=sys.stderr)
        return
    import datetime
    header = f"<!-- auto-generated by trends.py from {len(top)} top reels across {len(tags)} hashtags -->\n"
    open(f"{ROOT}/memory/TRENDS.md", "w").write(header + md + "\n")
    print(f"[trends] analyzed {len(top)} reels -> memory/TRENDS.md")


if __name__ == "__main__":
    main()
