// AUTO-GENERATED by scripts/gen_custom_registry.py — do not edit by hand.
// Maps a custom scene's component name -> the agent-authored React component.
import React from "react";
import ChatUI from "./ChatUI";
import ChineseRoom from "./ChineseRoom";
import InterpretabilityDash from "./InterpretabilityDash";
export const CUSTOM: Record<string, React.FC<any>> = {
  ChatUI: ChatUI,
  ChineseRoom: ChineseRoom,
  InterpretabilityDash: InterpretabilityDash,
};
